version: "3.3"
services:

  map-it:
    build:
      cache_from:
        - hiddewie/map-it:master
    image: hiddewie/map-it:$GITHUB_REF_NAME

  map-it-bounds:
    build:
      cache_from:
        - hiddewie/map-it-bounds:master
    image: hiddewie/map-it-bounds:$GITHUB_REF_NAME

  map-it-import:
    build:
      cache_from:
        - hiddewie/map-it-import:master
    image: hiddewie/map-it-import:$GITHUB_REF_NAME
