version: "3.3"

services:

  map-it:
    depends_on:
      - postgres-osm
    build:
      context: .
      dockerfile: Dockerfile
    image: hiddewie/map-it
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./data/combined.tif
        target: /map-it/data/combined.tif
      - type: bind
        source: ./output
        target: /map-it/output

  map-it-bounds:
    depends_on:
      - postgres-osm
    build:
      context: .
      dockerfile: bounds.Dockerfile
    image: hiddewie/map-it-bounds
    env_file:
      - .env

  map-it-import:
    depends_on:
      - postgres-osm
    build:
      context: .
      dockerfile: import.Dockerfile
    image: hiddewie/map-it-import
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./data
        target: /data

  map-it-kosmtik:
    depends_on:
      - postgres-osm
    build:
      context: .
      dockerfile: kosmtik.Dockerfile
    ports:
      - "6789:6789"
    volumes:
      - type: bind
        source: ./data/combined.tif
        target: /map-it/data/combined.tif
    environment:
      - PGHOST=postgres-osm
      - PGUSER=osm

  # Dependencies
  postgres-osm:
    image: postgis/postgis:15-3.3-alpine
    command: postgres -c log_min_duration_statement=1000
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: ./data/postgres-data
        target: /var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
