name: GitHub Actions Demo

on:
  push: {}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/hiddewie/map-it-bounds

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=ghcr.io/hiddewie/map-it-bounds:master
            type=registry,ref=ghcr.io/hiddewie/map-it-bounds:${{ github.ref }}
            type=registry,ref=ghcr.io/hiddewie/map-it-bounds:${{ github.sha }}
          cache-to: type=registry,ref=ghcr.io/hiddewie/map-it-bounds:${{ github.sha }},mode=max

  Test:
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - run: echo 1
